### ISSUE TITLE
Example 1 - use free tier eligible instance for hosting

### ISSUE THREAD

**Issue by winstonaws** [awsdocs/amazon-sagemaker-developer-guide#1]
In https://github.com/awsdocs/amazon-sagemaker-developer-guide/blob/master/doc_source/ex1-deploy-model.md

You should use ml.m4.xlarge, since it's eligible for free tier.

**Comment by mohanva** [comment]
Ok.. will do

**Comment by mohanva** [comment]
The source file updated.  Will go live on Friday.
