### ISSUE TITLE
When MAE = MSE

### ISSUE THREAD

**Issue by xsansha** [awsdocs/amazon-sagemaker-developer-guide#115]
Hi There,

I was going through the documentation and found that MAE = MSE.

Can you guys tell me in which scenario it will be equal and resembles the number mentioned in the doc?

https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-model-quality-metrics.html

Regards
Sanket Sharma

**Comment by xsansha** [comment]
Theoretically, it can be but practically I never saw.

**Comment by TEChopra1000** [comment]
@xsansha these numbers are only used for example purposes. They should not be taken to be real values.

**Comment by xsansha** [comment]
Still I suggest to correct it.
