### ISSUE TITLE
[Question] Get Sagemaker Neo Compilation Job Logs

### ISSUE THREAD

**Issue by samanvyatripathi** [awsdocs/amazon-sagemaker-developer-guide#182]
Hey, I'm trying to get some logs out of Sagemaker Neo (for example: Model size/parameters that have been reduced, fps etc) but I don't see anything documented on the topic. Would be great if you can help me out here. So, is there a provision to get such metrics or some logs that would give insight into the way the model has been optimized?

**Comment by minlu1021** [comment]
Hello, 
We are actively working on the feature to expose compilation logs, if your compilation job was created recently and it was successful, you can find logs on console, click compilation job -> monitor -> view logs. 
If you need more information about your compilation job or you couldn't find logs, please contact AWS support and provide the compilation job ARN, we should be able to help you and provide information you need.

**Comment by samanvyatripathi** [comment]
@minlu1021 
Hello, thanks for the information. I went to 'view logs' under the latest successful compilation job but it doesn't show me anything. Can you help me with some more information on what Log stream to create so it captures the logs that you are talking about?

> If you need more information about your compilation job or you couldn't find logs, please contact AWS support and provide the compilation job ARN, we should be able to help you and provide information you need.

Sure, I'll look into it.
