### ISSUE TITLE
GitHub/Other Git-based repo. does not exists

### ISSUE THREAD

**Issue by chanansh** [awsdocs/amazon-sagemaker-developer-guide#214]
in sagemaker notebook you can click to clone a repo. there is no "GitHub/Other Git-based repo." option or menu

<img width="300" alt="image" src="https://user-images.githubusercontent.com/5981644/167798806-9ee64d3b-d572-4c07-a4cd-8b9c339aabf0.png">

**Comment by IvyBazan** [comment]
@chanansh  I believe this is in reference to the following documentation page: 
https://docs.aws.amazon.com/en_us/sagemaker/latest/dg/nbi-git-resource.html
The option described in this documentation refers to cloning a repo from the Amazon SageMaker console, not from within a Notebook instance
