### ISSUE TITLE
Sentence doesn't feel right

### ISSUE THREAD

**Issue by gopinaath** [awsdocs/amazon-sagemaker-developer-guide#22]
I believe the following line in [Automatic Model Tuning](https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning.html) needs to be rephrased.

> Before you start using hyperparameter tuning, you a well-defined machine learning problem, including the following:

**Comment by eslesar-aws** [comment]
@gopinaath Thank you for catching this! We appreciate your help in improving our documentation. This has been fixed, and the change should now be reflected here.
