### ISSUE TITLE
feature group arn format seems incorrect

### ISSUE THREAD

**Issue by aarora79** [awsdocs/amazon-sagemaker-developer-guide#220]
Please see  FeatureStoreBatchIngestion.py section on page https://docs.aws.amazon.com/sagemaker/latest/dg/batch-ingestion-spark-connector-setup.html. The following line has the string "Amazon SageMaker" in the ARN which should be just "sagemaker":

`feature_group_arn = "arn:aws:Amazon SageMaker:us-west-2:<your-account-id>:feature-group/<your-feature-group-name>"` should 

probably be something like
region="replace-with-sagemaker-region"
fg_name = "replace-with-your-feature-group-name"
account_id = "replace-with-your-account-id"

`feature_group_arn = f"arn:aws:sagemaker:{region}:{account_id}:feature-group/{fg_name}"`

**Comment by easyj2j** [comment]
Thanks for catching this. Content has been updated.
