### ISSUE TITLE
S3 CORS policy looks wrong

### ISSUE THREAD

**Issue by yucchi-p** [awsdocs/amazon-sagemaker-developer-guide#225]
Hi team, 
I follow this documents, and setting S3 CORS policy. 

Give your users the ability to upload local files
https://docs.aws.amazon.com/sagemaker/latest/dg/canvas-set-up-local-upload.html
Add the following CORS policy:
`
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "POST"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposedHeaders": []
    }
]
   `

So, S3 returned this error.

> Unexpected key 'ExposedHeaders' found in params.CORSConfiguration.CORSRules[0]

It seems to be "ExposeHeaders", not "ExposedHeaders"

**Comment by easyj2j** [comment]
Thanks for catching this. Content will be updated shortly.

**Comment by teebkeng-aws** [comment]
I also received a ticket for this, and the fix in the developer guide went live yesterday: https://docs.aws.amazon.com/sagemaker/latest/dg/canvas-set-up-local-upload.html

The GitHub docs will reflect this update soon!

**Comment by yucchi-p** [comment]
Thank you, team!

**Comment by easyj2j** [comment]
Content updated
