### ISSUE TITLE
is there a way to have a studio instance pull code from a private repo?

### ISSUE THREAD

**Issue by tansaku** [awsdocs/amazon-sagemaker-developer-guide#227]
I was reading https://github.com/awsdocs/amazon-sagemaker-developer-guide/blob/master/doc_source/studio-tasks-git.md and was wondering if there is a way to have a studio instance pull code from a private repo?  like a way to add the necessary access tokens.

I know that we can do it for notebook git repos a la https://aws.amazon.com/blogs/machine-learning/amazon-sagemaker-notebooks-now-support-git-integration-for-increased-persistence-collaboration-and-reproducibility/ but wondering about studio git instances

and/or is there a way to the git URL for the git instance that is automatically associated with a studio instance?

**Comment by IvyBazan** [comment]
Hi @tansaku, you can clone a private repo using the same process. When you enter the URL of the private repo, you are prompted for your GitHub credentials.
