### ISSUE TITLE
DeepAR how it works minor typo. 

### ISSUE THREAD

**Issue by araitats** [awsdocs/amazon-sagemaker-developer-guide#24]
amazon-sagemaker-developer-guide/doc_source/deepar_how-it-works.md

zi1t and zi2t must be xi1t and xi2t, respectively. 

Cheers.

**Comment by araitats** [comment]
So as the corresponding AWS developer guide...
https://docs.aws.amazon.com/sagemaker/latest/dg/deepar_how-it-works.html

**Comment by easyj2j** [comment]
Fixed 8/14/18, 3cf5a52b
