### ISSUE TITLE
The diagram is not correct 

### ISSUE THREAD

**Issue by entest-hai** [awsdocs/amazon-sagemaker-developer-guide#247]
Please update [this diagram](https://github.com/awsdocs/amazon-sagemaker-developer-guide/blob/master/doc_source/how-it-works-training.md)

Ec2 Container Registry ==> Elastic Container Registry

**Comment by p-nanimal** [comment]
This diagram was updated as requested.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
