### ISSUE TITLE
A mention of SageMaker ProcessingJob in automating-sagemaker-with-eventbridge.md would be useful

### ISSUE THREAD

**Issue by aarora79** [awsdocs/amazon-sagemaker-developer-guide#262]
This page https://github.com/awsdocs/amazon-sagemaker-developer-guide/blob/master/doc_source/automating-sagemaker-with-eventbridge.md does not mention SageMaker ProcessingJob in the list under "SageMaker events monitored by EventBridge" giving the impression that capturing SageMaker ProcessingJob is not supported (but it is). It would be very helpful if this list is updated to include SageMaker Processing and an example is provided.

Further, it would also be helpful if a sample JSON is provided for the EventBridge rule pattern because if someone is creating a rule programatically then they need a reference.
```
{
  "source": ["aws.sagemaker"],
  "detail-type": ["SageMaker Processing Job State Change"],
  "detail": {
    "ProcessingJobStatus": ["Failed", "Completed", "Stopped"]
  }
}
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
