### ISSUE TITLE
"Deploy Endpoints from Model Data" link does not exist

### ISSUE THREAD

**Issue by perrozzi** [awsdocs/amazon-sagemaker-developer-guide#263]
in page 
https://docs.aws.amazon.com/sagemaker/latest/dg/pytorch.html
corresponding to github page https://github.com/awsdocs/amazon-sagemaker-developer-guide/tree/master/doc_source/pytorch.md
there is a broken link: 

``I have a PyTorch model that I trained outside of SageMaker, and I want to deploy it to a SageMaker endpoint
For more information, see [Deploy Endpoints from Model Data](https://sagemaker.readthedocs.io/en/stable/using_pytorch.html#deploy-endpoints-from-model-data).``

the bookmark
https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#deploy-endpoints-from-model-data
is not available

**Comment by prashantlv** [comment]
@perrozzi, It is working. Please check again.

**Comment by easyj2j** [comment]
Verified it's working.
