### ISSUE TITLE
SageMaker image tags ambiguity

### ISSUE THREAD

**Issue by donjude** [awsdocs/amazon-sagemaker-developer-guide#291]
IHAC who encountered an issue with the documentation: https://github.com/awsdocs/amazon-sagemaker-developer-guide/blob/main/doc_source/ecr-us-east-1.md#xgboost-us-east-1.title because of ambiguous SageMaker XGBoost image tag. From the documentation the customer was using the tag as `0.90-1` and the complete image uri:
`683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:0.90-1`

But further investigations conducted shows that the tag should rather be `0.90-1-cpu-py3` for the complete image uri `683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:0.90-1-cpu-py3`

**Suggestion:** 
I would suggest that another column (see table below) for `Tag` should be added to specify all the image tags for all the available SageMaker images, unless there is some sort of consistency in the tagging.

| Registry path | Version | Package version | Job types (image scope) | Tag |
| :--------: | :--------: | :--------: | :--------: | :--------: |
| 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost: | 1.5-1 | 1.5.2 | inference, training | 1.5.2 |
| 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost: | 0.90-1 | 0.90 | inference, training | 0.90-1-cpu-py3 |

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
