### ISSUE TITLE
How does XGBoost calculate NDCG?

### ISSUE THREAD

**Issue by GiteshKhannaOYO** [awsdocs/amazon-sagemaker-developer-guide#36]
NDCG is based on relevance. until we don't have any base to compare, how is XGBoost calculating the relevance?

**Comment by aws-rbs** [comment]
The updated XGBoost implementation is base on the open source version. The code for calculating NDCG is provided here: https://github.com/dmlc/xgboost/blob/master/src/metric/rank_metric.cc 
Apologies for the tardy reply, this issue got lost for awhile.
