### ISSUE TITLE
Create an EI Endpoint with Boto3 example needs enhancement

### ISSUE THREAD

**Issue by 47billz** [awsdocs/amazon-sagemaker-developer-guide#37]
I see 2 problems in the section "Create an EI Endpoint with Boto 3"

https://github.com/awsdocs/amazon-sagemaker-developer-guide/blob/master/doc_source/ei-endpoints.md#L79

1. In L91 ```endpoint_config_name``` is created, only printed, but never used again

2. In L110 ```sagemaker.create_endpoint(...)``` Is used incorrectly . The function requires ```EndpointName``` and ```EndpointConfigName``` as   kwargs . See: 
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_endpoint

If I am not mistaken and I were to fix the example, it would be as follows:
```python
# Create Endpoint Configuration
import boto3
from time import gmtime, strftime

sagemaker = boto3.client('sagemaker')
endpoint_config_name = 'ImageClassificationEndpointConfig-' + strftime("%Y-%m-%d-%H-%M-%S", gmtime())
print(endpoint_config_name)
create_endpoint_config_response=sagemaker.create_endpoint_config(
    EndpointConfigName=endpoint_config_name,
    ProductionVariants=[{
        'InstanceType':'ml.m4.xlarge',
        'InitialInstanceCount':1,
        'ModelName':model_name,
        'VariantName':'AllTraffic',
        'AcceleratorType':'ml.eia1.medium'}])

print("Endpoint Config Arn: " + create_endpoint_config_response['EndpointConfigArn'])
```
and 

```python
endpoint_name = 'ImageClassificationEndpoint-' + strftime("%Y-%m-%d-%H-%M-%S", gmtime())
endpoint_response = sagemaker.create_endpoint(
    EndpointName=endpoint_name,
    EndpointConfigName=endpoint_config_name)
```

**Comment by eslesar-aws** [comment]
This was fixed by #38 

Thank you for your contribution, @47billz
