### ISSUE TITLE
Change num_classes hyperparameter for SageMaker Incremental training

### ISSUE THREAD

**Issue by PatrickWalsh6079** [awsdocs/amazon-sagemaker-developer-guide#39]
I am performing incremental training on a model I already trained in SageMaker. I want to add data to the existing classes as well as create new classes. The first model had 4 classes (num_classes = 4) but I want to keep those classes as well as add 3 additional classes.

![Capture](https://user-images.githubusercontent.com/34382502/56041082-e3d33480-5d05-11e9-9c20-6e19ae8eede3.JPG)

The documentation says that the num_classes hyperparameter must be the same when doing incremental training. But if that is the case, that means I cannot add classes to my existing model, I would have to start from scratch each time I wanted to change the number of classes. Is this accurate? Or is there a way to update an existing model and change the number of classes it is trained on?

Thanks in advance!

Here is the example notebook I am using for the incremental training job:
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/imageclassification_caltech/Image-classification-incremental-training-highlevel.ipynb

**Comment by eslesar-aws** [comment]
This is correct. You can't use incremental training if you want to change the number of classes in a classification model.
