### ISSUE TITLE
How can I treat my python scripts as separate services?

### ISSUE THREAD

**Issue by aviskarkc10** [awsdocs/amazon-sagemaker-developer-guide#43]
In every ML problem you will almost always have the following three steps:
1. Prepare dataset.
2. Train the model.
3. Generate predictions.

So my project will most probably look like this:
```
ml-project
|
|--- data.py        // prepare and save the dataset ready to be fed into the model.
|
|--  train.py       // train and save the model.
|
|--- predict.py     // generate predictions.
```

Because of the three scripts I need to run, I might have to create three separate docker images and publish them. Is there a mechanism like `docker-compose` where I can treat each script as a service and run them through `sagemaker`? If not what is the best option for handling these cases other than publishing three different docker images?

**Comment by eslesar-aws** [comment]
Hello Aviskar,

This repository is for issues with the existing documentation. For assistance with using SageMaker, please start by asking your question at our online forum:

https://forums.aws.amazon.com/forum.jspa?forumID=285
