### ISSUE TITLE
description for the image_shape parameter seems incorrect. 

### ISSUE THREAD

**Issue by jlwebuser** [awsdocs/amazon-sagemaker-developer-guide#44]
When I specify an image_shape = '3,416,416' the API errors out as follows:

Customer Error: The value '3,416,416' is not valid for the 'image_shape' hyperparameter which expects one of the following: a string which matches the pattern '^[1-9][0-9]*$'; or an integer between 300 and 10000 (caused by ValidationError)

It appears that it wants a single integer value which i assume is the size of the square image.

if it matters i'm training a resnet-50 network.

**Comment by aaronmarkham** [comment]
Hi @jlwebuser - apologies for the slow reply. For support and help with using SageMaker, please try the forum: https://forums.aws.amazon.com/forum.jspa?forumID=285
