### ISSUE TITLE
is it wrong with the feature time series based on the frequency of the target time series?

### ISSUE THREAD

**Issue by KaishuaiXu** [awsdocs/amazon-sagemaker-developer-guide#55]
<img width="1097" alt="Screen Shot 2019-09-27 at 10 54 52" src="https://user-images.githubusercontent.com/26295036/65738769-8ac15680-e115-11e9-85d3-5263796f3730.png">
how do you define the feature "day-of-month" based on weekly series? One point in weekly data represents infomation in 7 days.

**Comment by aaronmarkham** [comment]
Hi @KaishuaiXu - apologies for the slow reply. For support and help with using SageMaker, please try the forum: https://forums.aws.amazon.com/forum.jspa?forumID=285
