### ISSUE TITLE
IAM Policy incomplete

### ISSUE THREAD

**Issue by seittema** [awsdocs/amazon-sagemaker-developer-guide#58]
On the page https://docs.aws.amazon.com/sagemaker/latest/dg/security_iam_id-based-policy-examples.html#nbi-ip-filter the example policy isn't valid json and incomplete. The Deny block is cut off.

>  {
> 
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Effect": "Allow",
>       "Action": "*",
>       "Resource": "*"
>     },
>     {
>       "Effect": "Deny",
>       "Action": "sagemaker:CreateEndpoint",
>       "Resource": [
>         "arn:aws:sagemaker:*:*:endpoint/*"
>       ]
>     {
>       "Effect": "Allow",
>       "Action": "sagemaker:CreateEndpoint",
>       "Resource": [
>         "arn:aws:sagemaker:*:*:endpoint/*"
>       ],
>       "Condition": {
>         "StringEquals": {
>           "aws:RequestTag/environment": "dev"
>         }
>       }
>     }
>   ]
> }

**Comment by TEChopra1000** [comment]
This policy has been updated. Thank you for filing the bug.

**Comment by easyj2j** [comment]
Overwritten
