### ISSUE TITLE
Provide supported versions of frameworks

### ISSUE THREAD

**Issue by alexwong** [awsdocs/amazon-sagemaker-developer-guide#61]
Currently there isn't a great place to find versioning support for frameworks supported by Sagemaker Neo. Since a great starting point are these docs and the notebooks we should provide some info here.

**Comment by mchoi8739** [comment]
The supported frameworks and operators were updated to the [Neo top node page](https://docs.aws.amazon.com/sagemaker/latest/dg/neo.html#neo-supported).
