### ISSUE TITLE
sagemaker studio tour missing/out of order steps

### ISSUE THREAD

**Issue by ezeeetm** [awsdocs/amazon-sagemaker-developer-guide#69]
regarding this section:
https://github.com/awsdocs/amazon-sagemaker-developer-guide/blob/master/doc_source/gs-studio-end-to-end.md#keep-track-of-machine-learning-experiments

- step 1 "Run the following cell..." refers to the 8th code cell in the notebook.  The previous 7 code cells need to be run first for the notebook to work, but are never referenced in the tour walkthrough doc.  The doc  goes from having the user clone the repo:

`git clone https://github.com/awslabs/amazon-sagemaker-examples.git`

straight to having the user run the 8th code cell in the notebook, skipping the first 7 code cells.

-  step 2 "Create trials and associate...." refers to code cell 11 in the notebook, but again jumps straight from cell 8 without ever running cells 9, or 10

**Comment by ezeeetm** [comment]
@juliensimon @eslesar-aws 
if you want to briefly outline what you _want_ the tour/walkthrough to look like here, I will submit a PR to fix

**Comment by easyj2j** [comment]
Updated in latest commit.
