### ISSUE TITLE
ResourceLimitExceeded for ml.m4.xlarge when running SageMaker studio demo in a new AWS account

### ISSUE THREAD

**Issue by ezeeetm** [awsdocs/amazon-sagemaker-developer-guide#70]
When walking through the SageMaker Studio tour :

https://docs.aws.amazon.com/sagemaker/latest/dg/gs-studio-end-to-end.html

for the first time in a new AWS account, the usual service limit issue is hit when running code cell [17] to create an endpoint to host the model.

`ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) when calling the CreateEndpoint operation: The account-level service limit 'ml.m4.xlarge for endpoint usage' is 0 Instances, with current utilization of 0 Instances and a request delta of 1 Instances. Please contact AWS support to request an increase for this limit.`

Suggestions:

- The "Prerequistes" section could address this proactively, with a link to the service limit increase page, or...
-  the notebook could be changed to use an instance type for the endpoint that does not have a default service limit of `0`

Please LMK which is preferable and I will submit a PR

**Comment by ezeeetm** [comment]
same with code cell [12]
it calls for 5 child weights to be tried:

`min_child_weights = [1, 2, 4, 8, 10]`

but the default number of instances across all training jobs in a new account is 4, and needs to be increased for the tour to work without errors.

Suggestion:
- add this to prerequsites section
- change the notebook to only try 4 values for `min_child_weights`


```ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) when calling the CreateTrainingJob operation: The account-level service limit 'Number of instances across all training jobs' is 4 Instances, with current utilization of 4 Instances and a request delta of 1 Instances. Please contact AWS support to request an increase for this limit.

**Comment by easyj2j** [comment]
Neither of these are doc issues. The notebook itself needs to be updated.

**Comment by aaronmarkham** [comment]
https://docs.aws.amazon.com/general/latest/gr/sagemaker.html states that the default limit for ml.m4.xlarge is 20, so in a typical account, you should be able to run the notebook without failure. Your administrator could have changed this though. You can contact support for a limit increase to fix your account to be able to run this notebook.
