### ISSUE TITLE
Dropdown label for crowd-entity-annotation

### ISSUE THREAD

**Issue by bhedayat** [awsdocs/amazon-sagemaker-developer-guide#76]
Hello,

Not necessarily an issue but more of a question.

I have a use case where I have many entity labels so I want to group them into broad types.
After I want to have a dropdown menu which when clicked shows the labels for that group. Is that possible to do with the crowd-entity-annotation?
https://github.com/awsdocs/amazon-sagemaker-developer-guide/blob/master/doc_source/sms-ui-template-crowd-entity-annotation.md

For example I have 20 entity labels for group 1 and 20 entity labels for group 2.

I want the turkers to see group 1 and group2 and click on them to show the finegrained entity labels

Any help would be appreciated. Thank you

**Comment by TEChopra1000** [comment]
@bhedayat I'm not sure. I don't think this will be possible because you have to input a specific format for the **labels** attribute but I suggest posting your question in the AWS Forums to see if someone else has any ideas: https://forums.aws.amazon.com/index.jspa.
