### ISSUE TITLE
How to open deployed endpoint on notebook?

### ISSUE THREAD

**Issue by rajan-blackboxes** [awsdocs/amazon-sagemaker-developer-guide#78]
I had deployed an endpoint using
`predictor = estimator.deploy(initial_instance_count=1,instance_type='ml.m4.xlarge')`.
 It is in service.

I found there no mention on opening endpoint on notebook on official doc
Is there any way to open deployed endpoint on notebook and predict again like this
`predictor.predict(test_data)`

Thank you for help.

**Comment by aaronmarkham** [comment]
For help, you can ask the community in the SageMaker forum: https://forums.aws.amazon.com/forum.jspa?forumID=285
