### ISSUE TITLE
Multiple crowd-entity-annotation

### ISSUE THREAD

**Issue by chijames** [awsdocs/amazon-sagemaker-developer-guide#85]
Hi,

As in the UI demo: https://github.com/aws-samples/amazon-sagemaker-ground-truth-task-uis/blob/master/text/sentiment-analysis-multiple-documents.liquid.html, we can put multiple documents in one page. I would like to know how to do this with crowd-entity-annotation. Specifically, annotating entities in several sentences in one page so that annotators can see the contextual information (the one just labeled). Thanks.

**Comment by TEChopra1000** [comment]
@chijames this may be possible, but we don't have a working example for it. This achieves something similar, where each sentence (or document) can be added to a separate tab, and workers can toggle between tabs: https://jsfiddle.net/6zjw2017/
