### ISSUE TITLE
Built-in algorithm pages should list which hyperparameters are tunable

### ISSUE THREAD

**Issue by athewsey** [awsdocs/amazon-sagemaker-developer-guide#90]
Algorithms packaged in SageMaker are able to exclude certain hyperparameters from eligibility for hyperparameter tuning via the `IsTunable` property in the [CreateAlgorithm API](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateAlgorithm.html).

At least some first-party algorithms (like [Semantic Segmentation](https://docs.aws.amazon.com/sagemaker/latest/dg/segmentation-hyperparameters.html)) seem to have quite restrictive settings: according to an error message I just got, several parameters like `gamma1/2`, `weight_decay` etc that you might expect to be tunable are not.

I can't find any documentation for this on the Semantic Segmentation algorithm in particular, but it also doesn't seem to be obviously present on many others.

(Would also like if the range was less restrictive for this particular algorithm, but that doesn't seem like a docs issue!)

**Comment by aws-rbs** [comment]
Almost all 1P algorithms have a sub-section in the documentation stating which hyper-parameters are tunable and their ranges: 

•	https://docs.aws.amazon.com/sagemaker/latest/dg/linear-learner-tuning.html#linear-learner-tunable-hyperparameters
•	https://docs.aws.amazon.com/sagemaker/latest/dg/lda-tuning.html#lda-tunable-hyperparameters
•	https://docs.aws.amazon.com/sagemaker/latest/dg/k-means-tuning.html#km-tunable-hyperparameters 
•	https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost-tuning.html#xgboost-tunable-hyperparameters 
•	And so on

Indeed, Semantic Segmentation is the only algorithm that does not have this section documented.  Working on the SS list of tunable HPs.
